//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopPolymersDb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LCNo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LCNo()
        {
            this.ProformaInvoices = new HashSet<ProformaInvoice>();
        }
    
        public int LC_Id { get; set; }

        [Required(ErrorMessage = "L/C no is required")]
        [Display(Name = "L/C NO")]
        public string LC_No { get; set; }

        [Required(ErrorMessage = "L/C Date is required")]
        [Display(Name = "L/C Date")]
        public DateTime LC_Date { get; set; }

        public List<LCNo> LCNO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaInvoice> ProformaInvoices { get; set; }
    }
}
