//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopPolymersDb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PaymentTerm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentTerm()
        {
            this.ProformaInvoices = new HashSet<ProformaInvoice>();
        }
    
        public int PT_Id { get; set; }

        [Required(ErrorMessage = "Payment term is required")]
        [Display(Name = "Payment Terms")]
        public string Payment_Term { get; set; }

        public List<PaymentTerm> PT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaInvoice> ProformaInvoices { get; set; }
    }
}
