//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TopPolymersDb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unite()
        {
            this.ProformaInvoices = new HashSet<ProformaInvoice>();
        }
    
        public int UnitId { get; set; }

        [Required(ErrorMessage = "Unit type is required")]
        public string Unit { get; set; }

        public List<Unite> Units { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaInvoice> ProformaInvoices { get; set; }
    }
}
